### ISSUE TITLE
Scoreboard opening/closing

### ISSUE THREAD

**Issue by biskfather** [Benzo00/benzo-scoreboard#1]
Scoreboard won't open on the keybin.
Only opens with /togglescoreboard
But will not close after, have to press f8 and type togglescoreboard for it to close

**Comment by Benzo00** [comment]
i dont know what your issue is but the command is ScoreBoard and not togglescoreboard, also make sure your on the latest esx with the registerinput in it.

**Comment by biskfather** [comment]
Well I know what I typed for it to open and /Scoreboard doesn't open it, /togglescoreboard does.
I know what I typed to open it.
And regardless, once its opened it won't close unless you open F8 and TYPE the command again
